version: "3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: always

    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web-secure.address=:443
      - --entrypoints.web.address=:80
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
      - --accesslog=true
      - --entrypoints.web.http.redirections.entryPoint.to=web-secure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443" # Docker sends requests on port 443 to Traefik on port 443

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/configuration/:/configuration/"
      - "/certs/traefik/:/certs/"

    networks:
      - wpsite

  # Database
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
      - /configuration/my.cnf:/etc/mysql/conf.d/config-file.cnf
      - /certs/:/certs/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    volumes:
      - /configuration/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /certs/:/certs/
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: https://cloudone.space/pma
    networks:
      - wpsite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/pma`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web-secure"
      - "traefik.http.routers.phpmyadmin.tls=true"

      - "traefik.http.middlewares.phpmyadmin-stripprefix.stripprefix.prefixes=/pma"
      - "traefik.http.middlewares.phpmyadmin.stripprefix.forceSlash=true"

      - "traefik.http.middlewares.custom_pma_repath.redirectregex.regex=pma$$"
      - "traefik.http.middlewares.custom_pma_repath.redirectregex.replacement=pma/"

      - "traefik.http.routers.phpmyadmin.middlewares=custom_pma_repath,phpmyadmin-stripprefix"

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ["./:/var/www/html/wp"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    working_dir: /var/www/html/wp

    networks:
      - wpsite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Path(`/`) || PathPrefix(`/wp`)"
      - "traefik.http.routers.wordpress.entrypoints=web-secure"
      - "traefik.http.routers.wordpress.tls=true"

      - "traefik.http.middlewares.wp_root_redirect.redirectregex.regex=\\.([a-zA-Z0-9]+)\\/$$"
      - "traefik.http.middlewares.wp_root_redirect.redirectregex.replacement=.$$1/wp/"
      - "traefik.http.routers.wordpress.middlewares=wp_root_redirect"

networks:
  wpsite:
volumes:
  db_data:
