version: '3'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - --entrypoints.web-secure.address=:443
      - "--entrypoints.web.address=:80"
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
      - "--accesslog=true"
    ports:
      - "80:80" 
      - "8080:8080"      
      - "443:443" # Docker sends requests on port 443 to Traefik on port 443

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/configuration/:/configuration/"
      - "/certs/:/certs/"

    networks:
      - wpsite

  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    # ports:
      # - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite

      # chtobi test fast

  my-app:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-app.rule=Path(`/healthcheck`)"
      - "traefik.http.routers.my-app.tls=true"
      - "traefik.http.routers.whoami.entrypoints=web"

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    # ports:
      # - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_SITEURL', 'https://' . $_SERVER['HTTPS_HOST'][1] . '/wp' );
    networks:
      - wpsite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=PathPrefix(`/wp`)"
      - "traefik.http.routers.wordpress.middlewares=wordpress-stripprefix"

      - "traefik.http.middlewares.wordpress-stripprefix.stripprefix.prefixes=/wp"
      - "traefik.http.routers.wordpress.entrypoints=web-secure"
      - "traefik.http.routers.wordpress.tls=true"
networks:
  wpsite:
volumes:
  db_data: