- name: Initialize everything
  hosts: localhost
  tasks:

    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        state: active
        api_token: "dop_v1_55c43834af6f014be76357221fa9befd71c11638a5bbd50fa2d3583a52983101"
        name: mydroplet
        size: s-1vcpu-2gb
        region: fra1
        image: ubuntu-20-04-x64
        wait_timeout: 500
        ssh_keys: [  
          "38713791", # Artem's key
          "37677128", # Arseniy's key  
        ]
        unique_name: true
      register: my_droplet

    - name: Show Droplet info
      ansible.builtin.debug:
        msg: |
          Droplet ID is {{ my_droplet.data.droplet.id }}
          First Public IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}
          First Private IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'private')).0.ip_address | default('<none>', true) }}

    - name: Add host to group 'just_created' with variable foo=42
      ansible.builtin.add_host:
        name: "cloud-one"
        hostname: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}"
