- name: Initialize everything
  gather_facts: False 
  hosts: localhost
  vars_prompt:
  - name: droplet_number
    prompt: How many virtual machines do you want to set up?
    private: false
    default: "1"
  tasks:
    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        state: active
        api_token: "{{ lookup('ansible.builtin.env', 'DO_API_KEY') }}"
        name: "droplet-{{ item }}"
        size: s-1vcpu-2gb
        region: fra1
        image: ubuntu-20-04-x64
        wait_timeout: 500
        # Note: those are IDs of the keys in our account
        # These don't give you access anywhere, unless you control the account
        # This is why whe keep this checked in. The API key,
        # which does give you control over the DO account, is passed via environment
        # variables.
        ssh_keys: [  
          "38713791", # Artem's key
          "37677128", # Arseniy's key  
        ]
        unique_name: true
      register: my_droplet
      with_sequence: "{{ droplet_number }}"
    - name: Show Droplet info
      ansible.builtin.debug:
        msg: |
          Droplet ID is "{{ item }}"
      with_items: "{{ my_droplet.results }}"

    - name: Add the newly created droplet(s) to the group of Ansible hosts
      ansible.builtin.add_host:
        name: "{{ item.data.droplet.name }}"
        ansible_host: "{{ (item.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}"
        ansible_user: root
        groups:
          - virtualmachines
      with_items: "{{ my_droplet.results }}"

- name: "Installation steps on the machine"
  hosts: virtualmachines
  tasks:
    - name: Wait for ssh to come up
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        delay: 10
        timeout: 30
       
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      become: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Install pyOpenSSL
      pip:
        name: pyOpenSSL
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install Docker Compose Module for Python
      pip:
        name: docker-compose
    - name: copy Docker Compose files
      copy:
        src: "{{ item }}"
        dest: "/kek/"
      loop:
        - docker-compose.yaml
    - name: copy db
      copy:
        src: "{{ item }}"
        dest: "/kek/db/"
      loop:
        - db/wordpress.sql
        
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /certs
        state: directory
        mode: '0755'

    # Creating a self-signed certificate
    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: /certs/certificate.key

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: /certs/certificate.pem
        privatekey_path: /certs/certificate.key
        provider: selfsigned

    # Send configuration files to the machine
    - name: Synchronization of src on the control machine to dest on the remote hosts
      ansible.posix.synchronize:
        src: configuration
        dest: /configuration

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /kek/
        files:
          - docker-compose.yaml
    
    - name: Create a subdomain for every droplet (useful if we have many machines)
      community.general.cloudflare_dns:
        zone: cloudone.space
        record: "{{ inventory_hostname }}"
        type: A
        value: "{{ ansible_ssh_host }}"
        # account_email: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_EMAIL') }}"
        api_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_TOKEN') }}"
        proxied: true

    - name: Show instructions to connect
      ansible.builtin.debug:
        msg: |
          All done! You can connect to the server on "{{ ansible_ssh_host }}"


