- name: Initialize everything
  gather_facts: False 
  hosts: localhost
  tasks:
    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        state: active
        api_token: "{{ lookup('ansible.builtin.env', 'DO_API_KEY') }}"
        name: mydroplet
        size: s-1vcpu-2gb
        region: fra1
        image: ubuntu-20-04-x64
        wait_timeout: 500
        # Note: those are IDs of the keys in our account
        # These don't give you access anywhere, unless you control the account
        # This is why whe keep this checked in. The API key,
        # which does give you control over the DO account, is passed via environment
        # variables.
        ssh_keys: [  
          "38713791", # Artem's key
          "37677128", # Arseniy's key  
        ]
        unique_name: true
      register: my_droplet

    - name: Show Droplet info
      ansible.builtin.debug:
        msg: |
          Droplet ID is {{ my_droplet.data.droplet.id }}
          First Public IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}
          First Private IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'private')).0.ip_address | default('<none>', true) }}

    - name: Add host to group 'just_created' with variable foo=42
      ansible.builtin.add_host:
        name: "cloud-one"
        ansible_host: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}"
        ansible_user: root
        groups:
          - virtualmachines

- name: "Installation steps on the machine"
  hosts: virtualmachines
  gather_facts: False 
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      become: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Install pyOpenSSL
      pip:
        name: pyOpenSSL
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install Docker Compose Module for Python
      pip:
        name: docker-compose
    - name: copy Docker Compose files
      copy:
        src: "{{ item }}"
        dest: "/kek/"
      loop:
        - docker-compose.yaml
    - name: copy db
      copy:
        src: "{{ item }}"
        dest: "/kek/db/"
      loop:
        - db/wordpress.sql
        
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /certs
        state: directory
        mode: '0755'

    # Creating a self-signed certificate
    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: /certs/certificate.key

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: /certs/certificate.pem
        privatekey_path: /certs/certificate.key
        provider: selfsigned

    # Send configuration files to the machine
    - name: Synchronization of src on the control machine to dest on the remote hosts
      ansible.posix.synchronize:
        src: configuration
        dest: /configuration

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /kek/
        files:
          - docker-compose.yaml
